---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  capacity:
    storage: 2Gi
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp