apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server-deployment
  namespace: deployment-lab
  labels:
    tier: application
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: demo_server
      env: dev
  template:
    metadata:
      labels:
        name: demo_server
        env: dev
    spec:
      containers:
      - name: hello
        image: vicxu/server
        env:
        - name: APP_NAME
          value: deployment_a
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    tier: proxy
  namespace: deployment-lab
spec:
  selector:
    name: demo_server
    env: dev  
  ports:
  - port: 8080
    targetPort: 8080