---
  - hosts: server
    become: true
    tasks:
      - name: Install nginx
        apt:
          name: nginx
          update_cache: yes
          state: latest
      - name: Enable HTTP firewall
        ufw:
          name: Nginx HTTP
          rule: allow
          state: enabled
      - name: Enable HTTPs firewall
        ufw:
          name: Nginx HTTPS
          rule: allow
          state: enabled
      - name: copy nginx config
        copy:
          src: "{{playbook_dir}}/nginx.conf"
          dest: "{{ nginx_config }}"
        vars:
          nginx_config: /etc/nginx/sites-available/default
      - name: reload nginx
        systemd:
          name: nginx.service
          state: reloaded