# -*- mode: ruby -*-
# vi: set ft=ruby :

# UBUNTU = "ubuntu/trusty64"
UBUNTU = "bento/ubuntu-16.04"
RHEL = "iamseth/rhel-7.3"


Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "machine-1" do |machine|
    machine.vm.network "private_network", ip: "192.168.51.15"
    machine.vm.box = UBUNTU
  end

end
