apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:latest
        args: ["--port", "3333"]
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
  namespace: default
spec:
  selector:
    app: whoami
  ports:
  - port: 3333
    targetPort: 3333
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: whoami
#   namespace: lab1
# spec:
#   rules:
#     - host : whoami
#       http:
#         paths:
#         - path: /
#           pathType: Exact
#           backend:
#             service:
#               name: whoami
#               port:
#                 number: 3333